
default_platform(:android)

# To run the lane, execute the following command:
# bundle exec fastlane firebase_distribution

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
        app: "1:702514088179:android:874baf96dedcaa55538f86",
        firebase_cli_token: "1//0307UJApEecAwCgYIARAAGAMSNwF-L9IrTGOmbKwC7wN9b5cQStvHeMjLik2RHkUQwoOwcWhbuh7vTR8YjM-MxQ2dvHBku5E3l6M",
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
        testers: "iibbrraahhimm00@gmail.com",
        release_notes: "Testing something with GitHub Actions, trying to push directly from master branch",
  )
  end
end